version: "2"
services:

  # Database
  pictureweb-mongo:
    image: mongo
    env_file:
     - .env
    volumes:
     - "${pictureweb_storage}/db:/data/db"
     
  # Services 
  pictureweb-web:
    image: tvvk/pictureweb-web
    links:
     - "pictureweb-mongo"    
    ports:
     - "8080:8080"
    env_file:
     - .env
    volumes:
     - "${pictureweb_storage}/images:/data/storage"
  pictureweb-flickr-fetcher:
    image: tvvk/pictureweb-flickr-fetcher
    links:
     - "pictureweb-mongo"    
    volumes:
     - "${pictureweb_storage}/images:/data/storage"
    env_file:
     - .env
  pictureweb-flickr-downloader:
    image: tvvk/pictureweb-flickr-downloader
    links:
     - "pictureweb-mongo"    
    env_file:
     - .env
    volumes:
     - "${pictureweb_storage}/images:/data/storage"
     
  # CI
  pictureweb-jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    ports:
     - "8081:8080"
     - "50000:50000"
    volumes:
     - "${pictureweb_storage}/jenkins:/var/jenkins_home"
     - /var/run/docker.sock:/var/run/docker.sock

